on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@14c6addfeb0bfb4b1d78fa1da89e5b08f7c6b3c3 # v3.4.1
        id: release
        with:
          command: manifest

      - name: Release executed
        run: echo '${{toJSON(steps.release)}}'

      - if: ${{ steps.release.outputs.releases_created }}
        name: Releas-ES created
        run: echo '${{toJSON(steps.release)}}'

      - if: ${{ steps.release.outputs.release_created }}
        name: Releas-E created
        run: echo '${{toJSON(steps.release)}}'

      # - if: ${{ steps.release.outputs.releases_created }}
      #   uses: actions/checkout@v3

      # - if: ${{ steps.release.outputs.releases_created }}
      #   uses: actions/setup-node@v3
      #     with:
      #       cache: 'yarn'
      #       node-version: 16
      #       registry-url: 'https://registry.npmjs.org'
      # - if: ${{ steps.release.outputs.releases_created }}
      #   run: yarn install --frozen-lockfile
